version: "3.3"
services:
  obsidian-node:
    container_name: obsidian-node
    image: node:16.16.0-alpine3.16
    user: "node"
    working_dir: /home/node/app
    volumes:
        - ./:/home/node/app
        - C:\Users\Yonat\My Drive\University - knowlegde\.obsidian\plugins\math-jaxs:/home/node/dist
    command:
        - /bin/sh
        - -c
        - |
            cp styles.css ../dist/
            cp manifest.json ../dist/
            node --version
            npm --version
            npm i --loglevel=verbose
            npm run dev
